import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import ToasterProvider from '@/providers/toaster-provider'
import { SessionProv } from '@/providers/session-provider'


export const metadata: Metadata = {
  title: 'Dribble clon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProv>
          <ToasterProvider />
          <Navbar />
          {children}
          <Footer />
        </SessionProv>
      </body>
    </html>
  )
}
